# Generated by Django 4.2.7 on 2025-10-21 12:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(editable=False, help_text='Unique case identifier', max_length=20, unique=True)),
                ('beneficiary_name', models.CharField(max_length=200)),
                ('beneficiary_email', models.EmailField(max_length=254)),
                ('beneficiary_phone', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(help_text='Password for beneficiary portal access', max_length=128, validators=[django.core.validators.MinLengthValidator(8)])),
                ('deceased_name', models.CharField(max_length=200)),
                ('case_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Beneficiary Case',
                'verbose_name_plural': 'Beneficiary Cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_is_beneficiary', models.BooleanField(default=True, help_text='True if sent by beneficiary, False if sent by admin')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='portal.beneficiarycase')),
                ('sender_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_visible_to_beneficiary', models.BooleanField(default=True, help_text='Whether this document is visible in the beneficiary portal')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='portal.beneficiarycase')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('BANK_ACCOUNT', 'Bank Account'), ('REAL_ESTATE', 'Real Estate'), ('VEHICLE', 'Vehicle'), ('INVESTMENT', 'Investment'), ('CRYPTOCURRENCY', 'Cryptocurrency'), ('DIGITAL_ASSET', 'Digital Asset'), ('PERSONAL_PROPERTY', 'Personal Property'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('estimated_value', models.DecimalField(decimal_places=2, help_text='Estimated value in USD', max_digits=12)),
                ('status', models.CharField(choices=[('UNCLAIMED', 'Unclaimed'), ('PROCESSING', 'Processing'), ('READY_FOR_TRANSFER', 'Ready for Transfer'), ('COMPLETED', 'Completed')], default='UNCLAIMED', max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Internal notes (not visible to beneficiary)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='portal.beneficiarycase')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-created_at'],
            },
        ),
    ]
