# Generated by Django 4.2.7 on 2025-10-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The question', max_length=500)),
                ('answer', models.TextField(help_text='The answer (HTML allowed)')),
                ('icon', models.CharField(default='bi-info-circle', help_text='Bootstrap icon class (e.g., bi-info-circle)', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this FAQ is visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_phone', models.CharField(default='+1 (800) 555-0199', help_text='Support phone number displayed throughout the site', max_length=20)),
                ('support_email', models.EmailField(default='support@dglegacy.com', help_text='Support email address', max_length=254)),
                ('company_address', models.TextField(default='123 Legacy Street, Suite 100\nNew York, NY 10001', help_text='Company physical address')),
                ('business_hours', models.CharField(default='Mon-Fri: 9AM - 6PM EST', help_text='Business operating hours', max_length=100)),
                ('estimated_completion_time', models.CharField(default='4-12 weeks', help_text='Estimated time for case completion', max_length=50)),
                ('identity_verification_time', models.CharField(default='3-5 business days', help_text='Time for identity verification', max_length=50)),
                ('document_preparation_time', models.CharField(default='5-7 business days', help_text='Time for document preparation', max_length=50)),
                ('legal_review_time', models.CharField(default='2-3 business days', help_text='Time for legal review', max_length=50)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn page URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('login_help_text', models.TextField(default='Your case number and password were provided by our agency.', help_text='Help text shown on login page')),
                ('response_time_message', models.CharField(default='We typically respond within 24 hours', help_text='Message about support response time', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('UNCLAIMED', 'Unclaimed'), ('PROCESSING', 'Processing'), ('READY_FOR_TRANSFER', 'Ready'), ('COMPLETED', 'Completed')], default='UNCLAIMED', max_length=30),
        ),
    ]
