# Generated by Django 4.2.7 on 2025-10-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_faq_sitesettings_alter_asset_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDescriptionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Standard Inheritance', 'Complex Estate')", max_length=200)),
                ('description', models.TextField(help_text='Case description template. Use {{deceased_name}} and {{beneficiary_name}} as placeholders.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Case Description Template',
                'verbose_name_plural': 'Case Description Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Welcome Message', 'Document Request')", max_length=200)),
                ('subject', models.CharField(help_text='Default subject line', max_length=200)),
                ('content', models.TextField(help_text='Message content. Use {{beneficiary_name}} and {{case_number}} as placeholders.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
                'ordering': ['name'],
            },
        ),
    ]
