# Generated by Django 4.2.7 on 2025-10-21 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0003_casedescriptiontemplate_messagetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploaded_by_beneficiary',
            field=models.BooleanField(default=False, help_text='True if uploaded by beneficiary, False if uploaded by admin'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who uploaded this (null if uploaded by beneficiary)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
